module.exports = {
    //  By default, Vue CLI assumes your app will be deployed at the root of a domain, 
    // e.g. https://www.my-app.com/. If your app is deployed at a sub-path, 
    // you will need to specify that sub-path using this option. 
    //  For example, if your app is deployed at https://www.foobar.com/my-app/, set publicPath to '/my-app/'.
    //
    //  The value can also be set to an empty string ('') or a relative path (./) so that all assets are 
    // linked using relative paths. This allows the built bundle to be deployed under any public path, 
    // or used in a file system based environment like a Cordova hybrid app.
    "publicPath": "/",

    //  The directory where the production build files will be generated in when running 
    // vue-cli-service build. Note the target directory will be removed before 
    // building (this behavior can be disabled by passing --no-clean when building).
    "outputDir": "dist",

    //  A directory (relative to outputDir) to nest generated static assets (js, css, img, fonts) under.
    "assetsDir": "",

    //  Specify the output path for the generated index.html (relative to outputDir). 
    // Can also be an absolute path.
    "indexPath": "index.html",

    //  By default, generated static assets contains hashes in their filenames for better 
    // caching control. However, this requires the index HTML to be auto-generated by Vue CLI. 
    // If you cannot make use of the index HTML generated by Vue CLI, you can disable filename 
    // hashing by setting this option to false.
    "filenameHashing": true
}